services:
  community-front:
    image: ${COMMUNITY_FRONT_IMAGE:-community-front:latest}
    container_name: community-front
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
